[config]
# 控制 0x1xxx
RELOCATION               = 0x1001
CONFIRM_RELOCATION       = 0x1002
TRANSLATION              = 0x1003
ROTATION                 = 0x1004
LIFTING                  = 0x1005
SET_SPEED                = 0x1006
SET_MOTOR_CONTROL        = 0x1007
SET_PALLET_ROTATION      = 0x1008
SET_HINT                 = 0x1009
PATH_NAVIGATION          = 0x100a
REMOTE_CONTROL           = 0x100b
EMERGENCY_STOP           = 0x100c
PALLET_ROTATION          = 0x100d
START_CHARGING           = 0x100e

# 地图 0x2xxx
PULL_MAP                 = 0x2001
PUSH_MAP                 = 0x2002
GET_AGV_POSITION         = 0x2003
GET_POINT_CLOUD          = 0x2004
GET_MAP_LIST             = 0x2005
GET_LOG_LIST             = 0x2006
GET_LOG_FILE             = 0x2007
BUILD_MAPPING            = 0x2008
LOCALIZATION_QUALITY     = 0x2009
CHECK_SHOWMAP_UPDATE_STATUS  = 0x200a
START_MAPPING            = 0x200b
SAVE_LOCATION_MAP        = 0x200c
END_MAPPING              = 0x200d
GET_MULTI_MAP_FILES      = 0x200e

# 任务 0x3xxx
QUERY_TASK               = 0x3001
START_TASK               = 0x3002
CANCEL_TASK              = 0x3003
PAUSE_TASK               = 0x3004
RESUME_TASK              = 0x3005
GET_RUN_TASK             = 0x3006
GET_EXECUTION_QUEUE      = 0x3007
WAIT_DURATION            = 0x3008
CONDITION_IF             = 0x3009
CONDITION_ENDIF          = 0x300a
GET_WARES               = 0x300b
DELETE_WARE              = 0x300c
MODIFY_WARE              = 0x300d
ADD_WARE                 = 0x300e

# 配网
GET_WIFI_LIST            = 0x4001
SET_WIFI_CONFIG          = 0x4002
GET_NETWORK_INTERFACE    = 0x4003

# 相机
GET_QR_CAMERA_DATA       = 0x5001
GET_RACK_NUMBER          = 0x5002

# 避障
GET_SCAN2POINTCLOUD     = 0X6001
GET_OBST_POLYGON        = 0X6002
GET_OBST_PCL            = 0X6003
GET_MODEL_POLYGON       = 0x6004

# 双臂机器人控制 0x7xxx
ENABLE_ROBOT             = 0x7001
SET_COORDINATE_SYSTEM    = 0x7002
SET_TOOL                 = 0x7003
JOG_SINGLE_AXIS          = 0x7004
JOINT_MOTION             = 0x7005
LINEAR_MOTION            = 0x7006
ONE_CLICK_HOMING         = 0x7007
GET_TEACHIN_FILE_LIST    = 0x7008
GET_TEACHIN_FILE         = 0x7009
PUSH_TEACHIN_POINTS      = 0x700a
GET_TEACHIN_POINTS       = 0x700b
GET_ROBOT_STATE          = 0x700c
DELETE_TEACHIN_FILES     = 0x700d
TRIGGER_CAMERA           = 0x700e
MOVEL_CUSTOM             = 0x700f

# 其他
UPLOAD_FILE              = 0xf001
SET_OPERATING_MODE       = 0xf002
GET_OPERATING_MODE       = 0xf003
REBOOT_OR_POWEROFF       = 0xf004
SET_DATE_TIME            = 0xf005
GET_DATE_TIME            = 0xf006
TERMINAL_COMMAND         = 0xf007
OTA_UPGRADE              = 0xf008
GET_VELOCITY             = 0xf009
GET_MCU2PC               = 0xf00a
GET_CLIENTS              = 0xf00b
GET_SYSINFO              = 0xf00c
GET_MODEL_FILE           = 0xf00d
GET_CAMERA_POINT_CLOUD   = 0xf00e
GET_CAMERA_VIDEO_LIST    = 0xf00f
GET_CAMERA_VIDEO         = 0xf010
GET_ERRORS               = 0xf011
STOP_CHARGING            = 0xf012
SET_DO                   = 0xf013
WAIT_DI                  = 0xf014
STATION_QR_CODE_RECTIFY  = 0xf015
CLEAR_ERRORS             = 0xf016
GET_PLC_DIGITAL_IO       = 0xf017
GET_CHASSIS_INFO         = 0xf018
GET_BROKER_CONNECTION    = 0xf019
SET_RCS_ONLINE           = 0xf01a
SOFT_RESET               = 0xf01b
CHECK_FD_KEEP_ALIVE      = 0xfefc
GET_PROCESSES_INFO       = 0xfefd
HEART_BEAT               = 0xfefe
SET_LOG_LEVEL            = 0xfffe
UNKOWN_CMD               = 0xffff
